server:
  shutdown: immediate

oauth:
  endpoint.url: http://localhost:9090/auth

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub